version: "3.9"
networks:
    default:
        name: autogpt-network
services:
  redis-stack:
    hostname: redis-finx
    container_name: redis
    image: redis/redis-stack:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
      - "8001:8001"
    expose:
      - "6379"
      - "8001"
